Repository rancher/shepherd, pull requests merged in 2024-04, with the labels that each got.

#118 [Main] Add a Workflow That Verifies Changes
  .github/scripts/build-packages.sh
  .github/scripts/check-go-mod.sh
  .github/workflows/verify-changes.yaml
  .golangci.yaml
  clients/k3d/config.go
  clients/tfexec/tfexec.go
  extensions/kubectl/template.go
  extensions/rancherleader/rancherleader.go
  pkg/clientbase/common.go
  pkg/clientbase/ops.go
  pkg/schemas/management.cattle.io/v3/schema.go
Labels: automation-enhancement

#120 [2.8] Add a Workflow That Verifies Changes
  .github/scripts/build-packages.sh
  .github/scripts/check-go-mod.sh
  .github/workflows/verify-changes.yaml
  .golangci.yaml
  clients/k3d/config.go
  clients/tfexec/tfexec.go
  extensions/kubectl/template.go
  extensions/rancherleader/rancherleader.go
  pkg/clientbase/common.go
  pkg/clientbase/ops.go
  pkg/schemas/management.cattle.io/v3/schema.go
Labels: automation-enhancement

#122 [2.7] Add a Workflow That Verifies Changes
  .github/scripts/build-packages.sh
  .github/scripts/check-go-mod.sh
  .github/workflows/verify-changes.yaml
  .golangci.yaml
  clients/k3d/config.go
  clients/tfexec/tfexec.go
  extensions/kubectl/template.go
  extensions/rancherleader/rancherleader.go
  extensions/rke1/nodetemplates/nodetemplates.go
  pkg/clientbase/common.go
  pkg/clientbase/ops.go
  pkg/schemas/management.cattle.io/v3/schema.go
Labels: automation-enhancement

#90 [Main] Fix Response Body Reading in Ingresses Package
  extensions/ingresses/ingresses.go
Labels: priority/0

#91 [2.8] Fix Response Body Reading in Ingresses Package
  extensions/ingresses/ingresses.go
Labels: priority/0

#96 [2.7] Fix Response Body Reading in Ingresses Package
  extensions/ingresses/ingresses.go
Labels: priority/0

#110 Modify CreateNamespace to accept clusterID and projectName as inputs instead of norman project
  extensions/kubeapi/namespaces/create.go
Labels: automation-enhancement

#112 [2.8] Modify CreateNamespace to accept clusterID and projectName instead of norman project
  extensions/kubeapi/namespaces/create.go
Labels: automation-enhancement

#111 [2.7] Modify CreateNamespace to accept clusterID and projectName instead of norman project
  extensions/kubeapi/namespaces/create.go
Labels: automation-enhancement

#74 make out-of-tree helpers public for additional testing during upgrades
  extensions/charts/awsoutoftree.go
  extensions/charts/verify.go
  extensions/clusters/clusters.go
  extensions/kubectl/template.go
Labels: enhancement, area/release-testing, automation-enhancement

#143 [2.8] make out-of-tree helpers public for additional testing during upgrades
  extensions/charts/awsoutoftree.go
  extensions/charts/verify.go
  extensions/clusters/clusters.go
  extensions/kubectl/template.go
Labels: area/release-testing, automation-enhancement

#144 [2.7] make out-of-tree helpers public for additional testing during upgrades
  extensions/charts/awsoutoftree.go
  extensions/charts/verify.go
  extensions/clusters/clusters.go
  extensions/kubectl/template.go
Labels: area/release-testing, automation-enhancement

#134 [v2.9] Fix flaky nodescaling test cases
  extensions/machinepools/machinepools.go
  extensions/provisioning/creates.go
  extensions/rke1/nodepools/nodepools.go
Labels: area/release-testing, automation-fix

#141 [v2.8] Fix flaky nodescaling test cases
  extensions/machinepools/machinepools.go
  extensions/provisioning/creates.go
  extensions/rke1/nodepools/nodepools.go
Labels: area/release-testing, automation-fix

#142 [v2.7] Fix flaky nodescaling test cases
  extensions/machinepools/machinepools.go
  extensions/provisioning/creates.go
  extensions/rke1/nodepools/nodepools.go
Labels: area/release-testing, automation-fix

#103 Enable automated install of vsphere cpi/csi
  clients/rancher/catalog/clusterrepo.go
  extensions/charts/vsphereoutoftree.go
  extensions/cloudcredentials/vsphere/create.go
  extensions/clusters/clusters.go
  extensions/kubeapi/volumes/persistentvolumeclaims/persistentvolumeclaims.go
  extensions/machinepools/vsphere_machine_config.go
  extensions/provisioning/creates.go
  extensions/provisioning/verify.go
  extensions/provisioninginput/config.go
  extensions/rke1/nodetemplates/vsphere/create.go
  extensions/rke1/nodetemplates/vsphere_config.go
Labels: automation-enhancement

#145 [v2.9] Convert flaky Python CLI tests to Go
  clients/rancher/client.go
  clients/rancher/config.go
  clients/ranchercli/client.go
  extensions/cli/cli.go
Labels: area/release-testing
