Repository rancher/shepherd, pull requests merged in 2024-03, with the labels that each got.

#109 [2.8] machinepool config
  extensions/machinepools/machinepools.go
  extensions/nodes/node_status.go
  extensions/provisioning/creates.go
  extensions/provisioning/verify.go
  extensions/provisioninginput/config.go
  extensions/sshkeys/downloadsshkeys.go
Labels: automation-enhancement

#108 [2.7] enable machinePool settings and nodeReplace ssh support
  extensions/machinepools/machinepools.go
  extensions/nodes/node_status.go
  extensions/provisioning/creates.go
  extensions/provisioning/verify.go
  extensions/provisioninginput/config.go
  extensions/sshkeys/downloadsshkeys.go
Labels: automation-enhancement

#29 Refactor nodetemplates extension
  extensions/rke1/nodetemplates/aws/create.go
  extensions/rke1/nodetemplates/aws_config.go
  extensions/rke1/nodetemplates/azure/create.go
  extensions/rke1/nodetemplates/azure_config.go
  extensions/rke1/nodetemplates/harvester/create.go
  extensions/rke1/nodetemplates/harvester_config.go
  extensions/rke1/nodetemplates/linode/create.go
  extensions/rke1/nodetemplates/linode_config.go
  extensions/rke1/nodetemplates/nodetemplates.go
  extensions/rke1/nodetemplates/vsphere/create.go
  extensions/rke1/nodetemplates/vsphere_config.go
Labels: automation-enhancement

#21 [2.8] Refactor `nodetemplates` extension
  extensions/rke1/nodetemplates/aws/create.go
  extensions/rke1/nodetemplates/aws_config.go
  extensions/rke1/nodetemplates/azure/create.go
  extensions/rke1/nodetemplates/azure_config.go
  extensions/rke1/nodetemplates/harvester/create.go
  extensions/rke1/nodetemplates/harvester_config.go
  extensions/rke1/nodetemplates/linode/create.go
  extensions/rke1/nodetemplates/linode_config.go
  extensions/rke1/nodetemplates/nodetemplates.go
  extensions/rke1/nodetemplates/vsphere/create.go
  extensions/rke1/nodetemplates/vsphere_config.go
Labels: automation-enhancement

#22 [2.7] Refactor `nodetemplates` extension
  extensions/rke1/nodetemplates/aws/create.go
  extensions/rke1/nodetemplates/aws_config.go
  extensions/rke1/nodetemplates/azure/create.go
  extensions/rke1/nodetemplates/azure_config.go
  extensions/rke1/nodetemplates/harvester/create.go
  extensions/rke1/nodetemplates/harvester_config.go
  extensions/rke1/nodetemplates/linode/create.go
  extensions/rke1/nodetemplates/linode_config.go
  extensions/rke1/nodetemplates/nodetemplates.go
  extensions/rke1/nodetemplates/vsphere/create.go
  extensions/rke1/nodetemplates/vsphere_config.go
Labels: automation-enhancement

#119 [Main] Bump main Branch to Go 1.22
  go.mod
  go.sum
Labels: priority/0, automation-enhancement

#121 [2.8] Bump release/v2.8 Branch to Go 1.21
  go.mod
  go.sum
Labels: priority/0, automation-enhancement

#117 Update Rancher leader extension to use lease instead of configmap
  extensions/rancherleader/rancherleader.go
Labels: status/blocker, automation-fix

#113 Adding workflow for identifying stale PRs
  .github/workflows/stale-prs.yml
Labels: automation-enhancement
